const dbName = process.env.MONGO_INITDB_DATABASE || 'food_delivery';
const appDb = db.getSiblingDB(dbName);
appDb.createCollection('restaurants');
appDb.restaurants.createIndex({ id: 1 }, { unique: true });
appDb.createCollection('orders');
appDb.orders.createIndex({ id: 1 }, { unique: true });
appDb.orders.createIndex({ customer: 1, createdAt: -1 });
appDb.orders.createIndex({ restaurantId: 1, status: 1, createdAt: -1 });
appDb.orders.createIndex({ status: 1, createdAt: -1 });
appDb.createCollection('payments');
appDb.payments.createIndex({ orderId: 1 }, { unique: true });
appDb.createCollection('customers');
appDb.customers.createIndex({ email: 1 }, { unique: true });
appDb.createCollection('drivers');
appDb.drivers.createIndex({ availability: 1, location: '2dsphere' });
appDb.createCollection('deliveries');
appDb.deliveries.createIndex({ orderId: 1 }, { unique: true });
appDb.createCollection('notifications');
appDb.notifications.createIndex({ id: 1 }, { unique: true });
appDb.notifications.createIndex({ recipientId: 1, createdAt: -1 });
